# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

name: '1.0.$(Date:yyyyMMdd).$(rev:r)'
trigger:
- master

resources:
  repositories:
    - repository: templates
      type: git
      name: azure-cicd-templates
      ref: refs/heads/main

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Test
    displayName: Test Stage
    jobs:
      - job: Script
        steps:
          - script: |
              echo "add another task"
            displayName: Sample script
  - stage: Template

    jobs:
      - job: dockerBuild
        displayName: Docker build
        steps:
        - template: docker-build-and-push.yaml@templates
          parameters:
            imageName: harnoorpuniyani/boh-user-management
            imageTag: v0
            directory: .
            dockerRegistry: docker-harnoorpuniyani
      - job: multiArchBuild
        displayName: multi architecture build
        steps:
          - template: docker-multi-architecture-build-and-push.yaml@templates
            parameters:
              directory: .
              dockerRegistry: docker-harnoorpuniyani
              imageName: harnoorpuniyani/boh-user-management
              imageTag: $(Build.BuildNumber)
              architecture: linux/amd64,linux/arm64
    





# steps:
# - script: echo Hello, world!
#   displayName: 'Run a one-line script'

# - script: |
#     echo Add other tasks to build, test, and deploy your project.
#     echo See https://aka.ms/yaml
#   displayName: 'Run a multi-line script'
