# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

name: '1.0.$(Date:yyyyMMdd).$(rev:r)'
trigger:
  branches:
     include:
       - master
  batch: true

resources:
  repositories:
    - repository: templates
      type: git
      name: azure-cicd-templates
      ref: refs/heads/main

pool:
  vmImage: ubuntu-latest

stages:
  - stage: testing
    displayName: Test Stage
    jobs:
      - job: Script
        steps:
          # - script: |
          #     echo "add another task"
          #   displayName: Sample script
          - task: NodeTool@0
            inputs:
              versionSource: 'spec'
              versionSpec: '24.x'
              checkLatest: true
            displayName: install node
          - script: |
              npm ci
            displayName: install packages
          - script: |
              npm run test:coverage
            displayName: run test coverage

          - task: PublishCodeCoverageResults@2
            inputs:
              summaryFileLocation: coverage/clover.xml
            displayName: publsih code coverage

  - stage: Template
    dependsOn: testing
    jobs:
      - job: dockerBuild
        displayName: Docker build
        steps:
        - template: docker-build-and-push.yaml@templates
          parameters:
            imageName: harnoorpuniyani/boh-user-management
            imageTag: v0
            directory: .
            dockerRegistry: docker-harnoorpuniyani
      
      # - job: unitTesting
      #   displayName: unit Testing
      #   steps:
      #     - task: Docker@2
      #       inputs:
      #         command: login
      #         containerRegistry: docker-harnoorpuniyani
          
      #     - script: docker run --rm harnoorpuniyani/boh-user-management:v0 npm test

      - job: multiArchBuild
        displayName: multi architecture build
        steps:
          - template: docker-multi-architecture-build-and-push.yaml@templates
            parameters:
              directory: .
              dockerRegistry: docker-harnoorpuniyani
              imageName: harnoorpuniyani/boh-user-management
              imageTag: $(Build.BuildNumber)
              architecture: linux/amd64,linux/arm64
    





# steps:
# - script: echo Hello, world!
#   displayName: 'Run a one-line script'

# - script: |
#     echo Add other tasks to build, test, and deploy your project.
#     echo See https://aka.ms/yaml
#   displayName: 'Run a multi-line script'
